apiVersion: kubeadm.k8s.io/v1alpha3
kind: JoinConfiguration
token: ${K8S_KUBEADM_TOKEN}
tlsBootstrapToken: ${K8S_KUBEADM_TOKEN}
discoveryFile: ""
discoveryToken: ${K8S_KUBEADM_TOKEN}
discoveryTimeout: 5m0s
discoveryTokenAPIServers:
- ${K8S_API_ENDPOINT}
discoveryTokenUnsafeSkipCAVerification: true
nodeRegistration:
  name: ${HOSTNAME}
  criSocket: /var/run/dockershim.sock
  kubeletExtraArgs:
    node-labels: ${K8S_NODE_LABELS}